### ISSUE TITLE
unixbench fails with multiple permisison/command not found error on centos6

### ISSUE THREAD

**Issue by cburroughs** [GoogleCloudPlatform/PerfKitBenchmarker#126] opened 2015-02-23 17:02 UTC
```
test.json
[
 {"ip_address": "INTERNAL",
  "os_type": "rhel",
  "keyfile_path": "ME",
  "user_name": "ADMIN",
  "scratch_disk_mountpoints": "/tmp/google-pkb",
  "zone": "Siberia"}
]

./pkb.py --benchmarks=unixbench --machine_type=YOLO --static_vm_file=test.json --zone=YOLO --ip_addresses=EXTERNAL
```

```
make all
make[1]: Entering directory `/tmp/pkb/UnixBench'
Checking distribution of files
./pgms  exists
./src  exists
./testdir  exists
./results  exists
make[1]: Leaving directory `/tmp/pkb/UnixBench'

   #    #  #    #  #  #    #          #####   ######  #    #   ####   #    #
   #    #  ##   #  #   #  #           #    #  #       ##   #  #    #  #    #
   #    #  # #  #  #    ##            #####   #####   # #  #  #       ######
   #    #  #  # #  #    ##            #    #  #       #  # #  #       #    #
   #    #  #   ##  #   #  #           #    #  #       #   ##  #    #  #    #
    ####   #    #  #  #    #          #####   ######  #    #   ####   #    #

   Version 5.1.3                      Based on the Byte Magazine Unix Benchmark

   Multi-CPU version                  Version 5 revisions by Ian Smith,
                                      Sunnyvale, CA, USA
   January 13, 2011                   johantheghost at yahoo period com


1 x Dhrystone 2 using register variables  1 2 3 4 5 6 7 8 9 10

1 x Double-Precision Whetstone  1 2 3 4 5 6 7 8 9 10

1 x Execl Throughput  1 2 3

1 x File Copy 1024 bufsize 2000 maxblocks  1STDERR: Warning: Permanently added '10.15.14.242' (RSA) to the list of known hosts.
./src/syscall.c: In function main:
./src/syscall.c:93: warning: null argument where non-null required (argument 2)
sh: //kill_run: Permission denied
sh: 3dinfo: command not found
sh: runlevel: command not found

**********************************************
Run: "File Copy 1024 bufsize 2000 maxblocks": fstime: creat: Permission denied; aborting
```

**Comment by voellm** [comment] 2015-03-12 22:25
Carlos - As the dupped Unixbench expert do you have time to look into this?

**Comment by ehankland** [comment] 2015-03-12 22:37
I'm guessing that the permissions on /tmp/google-pkb were too strict for the benchmark to run. Can you try running "chmod a+w  /tmp/google-pkb" on the VM and then try running the test again?

**Comment by meteorfox** [comment] 2015-03-16 17:41
@voellm oh, I just noticed this. Sure I'll take a look.

@cburroughs did  you try @ehankland  suggestion?

It seems it errors out here:
https://code.google.com/p/byte-unixbench/source/browse/trunk/UnixBench/src/fstime.c#175

Definitely looks like permissions problems. @voellm What user creates the /tmp/google-pkgb?

**Comment by meteorfox** [comment] 2015-03-24 22:15
@ehankland 

What user (as in linux user) by default executes this line, is it root/sudoer?
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/dev/perfkitbenchmarker/package_managers.py#L200

Then, is that the same user that then executes the benchmark?

I tried this locally, and I can replicate it in Ubuntu, when using the static configuration, and user with sudo privileges that is not root. If I use root, it works fine, but if I use another user that I created, even when is part of sudoers, I get this error too.

**Comment by ehankland** [comment] 2015-03-24 22:25
Whatever user you specify in your static config file :  "user_name": "ADMIN",

And yes, that is the same user that executes the benchmark. I don't think the issue is with the pkb/ directory, but rather with the scratch disk directory "scratch_disk_mountpoints": "/tmp/google-pkb", since that is where UnixBench executes the copy test (also since in static configs this is user supplied and may not have the right set of permissions depending on what they did to set it up).

**Comment by meteorfox** [comment] 2015-03-24 23:16
Maybe we could improve the error handling here, and instead of letting it fail, we could check if the user provided in the static config has the right set of permission for the scratch directory.

What do you think?

**Comment by voellm** [comment] 2015-03-24 23:24
Yes we should ... overall we need to improve error handling and give more
informative messages.

On Tue, Mar 24, 2015 at 4:16 PM, Carlos Torres <notifications@github.com>
wrote:

> Maybe we could improve the error handling here, and instead of letting it
> fail, we could check if the user provided in the static config has the
> right set of permission for the scratch directory.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/126#issuecomment-85735798>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by meteorfox** [comment] 2015-03-25 18:00
I've narrowed down the problem.

So, the static_vm JSON file defines the scratch_disk_mountpoints property which the user assumed it was a string, but pkb actually expected an array of strings.

Pkb does not do schema validation of the JSON file, and since strings are indexable in python, when the UnixBench benchmarks executes Vm.GetScratchDir(), it indexes the string on [0], and in this case returns "/", and because the user is used is ADMIN and not root, and the command is running without sudo, it will return permission denied error.

This is why it works for a root user, and not a normal user.

@cburroughs 

Wrap the value of scratch_disk_mountpoints with square brackets [ ]  in your static_vm json file as follows:

```json 
{
  "ip_address": "INTERNAL",
  "os_type": "rhel",
  "keyfile_path": "ME",
  "user_name": "ADMIN",
  "scratch_disk_mountpoints": ["/tmp/google-pkb"],
  "zone": "Siberia"
}
```
If done correctly the pkb log output should output something like this as the shell command run over SSH when executing UnixBench and the benchmark should succeed to run.

```INFO     Running: /usr/bin/ssh ... cd /tmp/pkb/UnixBench && UB_TMPDIR=/tmp/google-pkb ./Run```

If done incorrectly, it will look as follows:
```INFO     Running: /usr/bin/ssh ... cd /tmp/pkb/UnixBench && UB_TMPDIR=/ ./Run```

@voellm @ehankland 
It seems to me we need to add more documentation around static_vm configurations, perhaps even sample configuration files that they can based their config from.

Also, I propose using something like a json schema to validate the config file. Here's a popular pytthon library, [jsonschema](https://python-jsonschema.readthedocs.org/en/latest/)

I'll make a pull request with unit test that fails by replicating this issue, and along with it we could include a fix for handling it.

**Comment by voellm** [comment] 2015-03-25 18:07
Agreed on the doc issues.  We have a tracking issue:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/40

I also think we need to have validation done up front in the runs.


On Wed, Mar 25, 2015 at 11:00 AM, Carlos Torres <notifications@github.com>
wrote:

> I've narrowed down the problem.
>
> So, the static_vm JSON file defines the scratch_disk_mountpoints property
> which the user assumed it was a string, but pkb actually expected an array
> of strings.
>
> Pkb does not do schema validation of the JSON file, and since strings are
> indexable in python, when the UnixBench benchmarks executes
> Vm.GetScratchDir(), it indexes the string on [0], and in this case returns
> "/", and because the user is used is ADMIN and not root, and the command is
> running without sudo, it will return permission denied error.
>
> This is why it works for a root user, and not a normal user.
>
> @cburroughs <https://github.com/cburroughs>
>
> Wrap the value of scratch_disk_mountpoints with square brackets [ ] in
> your static_vm json file as follows:
>
> {
>   "ip_address": "INTERNAL",
>   "os_type": "rhel",
>   "keyfile_path": "ME",
>   "user_name": "ADMIN",
>   "scratch_disk_mountpoints": ["/tmp/google-pkb"],
>   "zone": "Siberia"
> }
>
> If done correctly the pkb log output should output something like this as
> the shell command run over SSH when executing UnixBench and the benchmark
> should succeed to run.
>
> INFO Running: /usr/bin/ssh ... cd /tmp/pkb/UnixBench &&
> UB_TMPDIR=/tmp/google-pkb ./Run
>
> If done incorrectly, it will look as follows:
> INFO Running: /usr/bin/ssh ... cd /tmp/pkb/UnixBench && UB_TMPDIR=/ ./Run
>
> @voellm <https://github.com/voellm> @ehankland
> <https://github.com/ehankland>
> It seems to me we need to add more documentation around static_vm
> configurations, perhaps even sample configuration files that they can based
> their config from.
>
> Also, I propose using something like a json schema to validate the config
> file. Here's a popular pytthon library, jsonschema
> <https://python-jsonschema.readthedocs.org/en/latest/>
>
> I'll make a pull request with unit test that fails by replicating this
> issue, and along with it we could include a fix for handling it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/126#issuecomment-86150127>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by cmccoy** [comment] 2015-03-25 18:12
Validation was improved in #166 - in the next release. 

@meteorfox: we considered jsonschema before, and decided not to add a dependency. I'd be happy to revisit that though.

**Comment by meteorfox** [comment] 2015-03-25 18:23
@cmccoy yeah, if we only have one JSON schema to validate, I agree then it's overkill to add another dependency just for that.

**Comment by meteorfox** [comment] 2015-03-25 22:04
@cburroughs Please, if this solved your problem. Can you please close this issue? Thanks

**Closed** 2015-10-29 01:36 UTC
Labels: bug, help wanted, P1
