### ISSUE TITLE
AWS provider should default to use itsown storage service

### ISSUE THREAD

**Issue by tedhtchang** [GoogleCloudPlatform/PerfKitBenchmarker#1019] opened 2016-06-21 01:35 UTC
Hi,
When running the following command:
./pkb.py --cloud=AWS --benchmarks=object_storage_service 
it deploys a VM on AWS and then from the VM, it  runs this particular  benchmark on Google storage. I am assuming this is a bug or maybe it's by design?
One should expect AWS provider uses S3 instead of Google storage.

**Comment by noahl** [comment] 2016-06-21 16:45
It is by design, but I agree that the more intuitive behavior would be to run on the storage service from the same provider as the VM. I'm assigning this to myself, but I don't know how quickly I will have time to work on it. If you want to implement it yourself in the mean time, I would be glad to help.

**Comment by tedhtchang** [comment] 2016-06-22 19:07
@noahl 
Hi, thanks! No hurry. 
It works with explicit "--storage=AWS" just seem redundant.

**Comment by voellm** [comment] 2016-09-22 15:06
This is by design so I'm going to close this.  Really it should just default to Azure Blob storage :)

**Closed by voellm** 2016-09-22 15:06 UTC
Labels: enhancement, P1
