### ISSUE TITLE
azure vm creation errors

### ISSUE THREAD

**Issue by jdc0589** [GoogleCloudPlatform/PerfKitBenchmarker#860] opened 2016-03-07 19:13 UTC
I'm running in to errors with the VM creation portion of an fio benchmark in Azure.

Steps for (me) to reproduce:
1. confirm azure cli version: `0.9.9 (node: 5.2.0)`), and pkb version: `v1.2.0`.
2. set azure cli to asm mode
3. run `pkb --cloud Azure --benchmarks=fio --scratch_disk_type=standard --scratch_disk_size=100`
4. error: `d931267b MainThread fio(1/1) vm_util.py:292 ERROR    Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>)`

Full log, with personal data scrubbed: [pkb.log.txt](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/161922/pkb.log.txt)

**Comment by skschneider** [comment] 2016-03-07 23:42
Looks like Popen.communicate stdout from the `azure vm image list --json` command is being truncated:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/vm_util.py#L541
Python doc: https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate
There's a warning that "The data read is buffered in memory, so do not use this method if the data size is large or unlimited."

We should create an alternative method of getting the output. In this particular case, Python's json module could probably work directly with the stream rather than getting the entire stdout as a string, but there are plenty of other places where we're using vm_util.IssueCommand where stdout may also be too large.

Can you provide information about the environment in which you are running PKB? It could be useful for testing.

**Comment by jdc0589** [comment] 2016-03-08 14:53
The response is pretty large, I had manually been calling the same `images` method earlier in the day just to remind myself of azure's weird VM names; it is extremely slow, and large.

It would be weird if it was getting truncated, there is certainly enough free memory to handle the response, so it must be very specific issue in the subprocess  module (if thats even the issue). My python fu is weak though.

Environtment: 
- Latest OSX, recent macbook pro
- zsh 5.2

**Comment by skschneider** [comment] 2016-03-08 20:57
I'll try to reproduce this later with OS X and/or zsh. For now, you should be able to sidestep the image list command if you explicitly specify the image (e.g. `--image=...`)

The default images I'm getting for Azure are currently, by OS:
windows: `a699494373c04fc0bc8f2bb1389d6106__Windows-Server-2012-R2-20160229-en.us-127GB.vhd`
debian: `b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_4-LTS-amd64-server-20160222-en-us-30GB`
rhel: `0b11de9248dd4d87b18621318e037d37__RightImage-CentOS-7.0-x64-v14.2.1`

**Comment by jdc0589** [comment] 2016-03-08 21:30
@skschneider thanks, not sure why that didn't occur to me. thats got me past it for now.

**Comment by skschneider** [comment] 2016-03-10 02:35
I'm able to reproduce this with OS X 10.11.3 w/ bash. I'll work on a fix.

**Comment by skschneider** [comment] 2016-03-10 22:24
I've merged #878 into master. Please let us know if this solves your issue.

**Closed** 2016-03-28 18:07 UTC
Labels: bug, P1
