### ISSUE TITLE
AWS default zone does not support subnets

### ISSUE THREAD

**Issue by skschneider** [GoogleCloudPlatform/PerfKitBenchmarker#655] opened 2015-11-19 19:33 UTC
A client error (InvalidParameterValue) occurred when calling the CreateSubnet operation: Value (us-east-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1b, us-east-1c, us-east-1d, us-east-1e.

**Comment by ehankland** [comment] 2015-11-19 19:37
Works for me:
```
./pkb.py --benchmarks=cluster_boot --zone=us-east-1a --cloud=AWS
2015-11-19 11:35:15,384 7d7f673e MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/run_7d7f673e/pkb.log
2015-11-19 11:35:15,384 7d7f673e MainThread INFO     PerfKitBenchmarker version: v0.23.0-190-gbbef30e
2015-11-19 11:35:15,476 7d7f673e MainThread INFO     Flag values:
--zones=us-east-1a
--cloud=AWS
--benchmarks=cluster_boot
2015-11-19 11:35:15,507 7d7f673e MainThread cluster_boot(1/1) INFO     Provisioning resources for benchmark cluster_boot
2015-11-19 11:35:15,509 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-vpc --region=us-east-1 --cidr-block=10.0.0.0/16
2015-11-19 11:35:16,888 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 modify-vpc-attribute --region=us-east-1 --vpc-id vpc-5c64e438 --enable-dns-hostnames { "Value": true }
2015-11-19 11:35:17,618 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-tags --region=us-east-1 --resources vpc-5c64e438 --tags Key=owner,Value=ehankland Key=perfkitbenchmarker-run,Value=7d7f673e
2015-11-19 11:35:18,373 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 describe-vpcs --region=us-east-1 --filter=Name=vpc-id,Values=vpc-5c64e438
2015-11-19 11:35:19,097 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-internet-gateway --region=us-east-1
2015-11-19 11:35:19,810 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-tags --region=us-east-1 --resources igw-444e5721 --tags Key=owner,Value=ehankland Key=perfkitbenchmarker-run,Value=7d7f673e
2015-11-19 11:35:20,554 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 describe-internet-gateways --region=us-east-1 --filter=Name=internet-gateway-id,Values=igw-444e5721
2015-11-19 11:35:21,231 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 attach-internet-gateway --region=us-east-1 --internet-gateway-id=igw-444e5721 --vpc-id=vpc-5c64e438
2015-11-19 11:35:21,931 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 describe-route-tables --region=us-east-1 --filters=Name=vpc-id,Values=vpc-5c64e438
2015-11-19 11:35:22,629 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-route --region=us-east-1 --route-table-id=rtb-dc423fb8 --gateway-id=igw-444e5721 --destination-cidr-block=0.0.0.0/0
2015-11-19 11:35:23,337 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-subnet --region=us-east-1 --vpc-id=vpc-5c64e438 --cidr-block=10.0.0.0/24 --availability-zone=us-east-1a
2015-11-19 11:35:24,354 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-tags --region=us-east-1 --resources subnet-2f302076 --tags Key=owner,Value=ehankland Key=perfkitbenchmarker-run,Value=7d7f673e
2015-11-19 11:35:25,115 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 describe-subnets --region=us-east-1 --filter=Name=subnet-id,Values=subnet-2f302076
2015-11-19 11:35:25,823 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 create-placement-group --region=us-east-1 --group-name=perfkit-7d7f673e-fed6e18e1456 --strategy=cluster
2015-11-19 11:35:26,507 7d7f673e Thread-1 cluster_boot(1/1) INFO     Running: aws --output json ec2 describe-placement-groups --region=us-east-1 --filter=Name=group-name,Values=perfkit-7d7f673e-fed6e18e1456
```
The issue is that AWS zones are not the same across accounts. See this:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
The key bit is "Note that there's no way for you to coordinate Availability Zones between accounts."

**Comment by skschneider** [comment] 2015-11-19 19:45
I see. I'm trying to see if there's a way to pick a better default. If I run "aws ec2 describe-availability-zones", it doesn't even list us-east-1a. Maybe picking a value from that list could be enough.

**Comment by ehankland** [comment] 2015-11-19 21:47
I've seen at least one issue where people have tried to pass PKB an AWS region instead of a zone. I'd like to make it work either way -  this would also fix this problem because we could make the default "zone" us-east-1

**Comment by ehankland** [comment] 2015-11-24 18:35
This should be fixed by the above PR (since there is no longer a default zone, just a default region).

**Closed by ehankland** 2015-11-24 18:35 UTC
Labels: bug
