### ISSUE TITLE
Unable to run fio test on large memory EC2 instances

### ISSUE THREAD

**Issue by hurtz** [GoogleCloudPlatform/PerfKitBenchmarker#246] opened 2015-05-05 15:25 UTC
I think I've found a bug where the fio tests won't complete on instances that have a large amount of memory. In this case, I'm using a 36vCPU / 60GiB RAM instance on EC2, cr1.8xlarge. Here is where it appears the failure happens:

2015-05-04 20:27:14,819 f0012f2b MainThread fio(4/4) INFO     Running: /usr/bin/ssh -A -p 22 ubuntu@52.6.90.76 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o P                                                         referredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthenti                                                         cation=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/run_f0012f2b/perfkitbenchmarker_keyfile cat /proc/meminfo | grep MemTotal | awk '{print $2}'
2015-05-04 20:27:15,533 f0012f2b MainThread fio(4/4) ERROR    /scratch0 must be larger than 10x memory"

**Comment by voellm** [comment] 2015-05-20 03:34
Assigning to Stanley to check this out....  since this bug was first opened we've revamped a log the the flags.

However this message should likely be a warning vs error.  What its trying to do by asking for 10x more disk space than memory is to prevent caching.

**Comment by srinivaslpalli** [comment] 2015-07-20 09:35
I am also seeing this issue : 
How to workaround this issue ?  I am using PerfKitBenchmarker-0.17.0 version.

**Comment by voellm** [comment] 2015-07-20 12:31
Can you please share the log message and benchmark that is failing.  Thanks.

**Comment by stfeng** [comment] 2015-07-20 22:01
srinivasipalli@

I think this is by design, the benchmark by default wants to ensure the disk is at least 10x larger than memory. So if you are using a VM with large memory (60GB in this case), you can ask pkb.py to create a scratch disk of larger size (1TB, eg.) by specifying the following flag:

--scratch_disk_size = 1000

Althernatively, you can change this disk-to-memory ratio requirement by specifying the following flag when you run the fio benchmark:

--memory_multiple = 0 (which will basically disable this check)

**Comment by voellm** [comment] 2015-07-20 22:15
@srinivaslpalli / @hurtz 

If stfeng's reply addresses you concern please let me know and I'll close the issue.

**Comment by srinivaslpalli** [comment] 2015-07-21 14:24
yes, it worked with "--memory_multiple=0" flag ... thanks much !!

**Closed** 2015-07-21 20:45 UTC
Labels: bug, P1
