### ISSUE TITLE
Benchmarker releases after 1.0.1 will not reuse available OpenStack Floating IPs

### ISSUE THREAD

**Issue by cbhall** [GoogleCloudPlatform/PerfKitBenchmarker#854] opened 2016-02-29 22:30 UTC
With PerfKit Benchmarker version 1.0.1, OpenStack Floating IPs that had been created but were currently unused were being reused by Benchmarker.  In later releases (1.1.0 and 1.2.0) Benchmarker will never reuse an existing (but currently unused) Floating IP, but will instead always attempt to create a new one.  In my tests, not reusing an existing Floating IP will result in a Benchmarker failure if no more Floating IPs can be created.

I believe I know what the problem is.  In the Bencharker version 1.0.1 code in providers/openstack/os_network.py, it looks for available existing Floating IPs with:
```
            floating_ips = self.__nclient.floating_ips.findall(
                fixed_ip=None,
                pool=self.ip_pool_name
            )
```
In the later releases, this code was changed to:
```
            floating_ips = self.__nclient.floating_ips.findall(
                fixed_ip=None,
                pool=self.ip_pool_name,
                status='Down'
            )
```
The problem is that Benchmarker is using the OpenStack v2.0 API which is documented at http://docs.clouda.ca/api/api-ref-compute-v2-ext.html.  In that API a 'status' value is not returned by the 'List Floating IPs' API call.  As an example, dumping the result of that API call on my OpenStack deployment, I see a result that looks like this (with the ip obscured):
`{"floating_ips": [{"instance_id": null, "ip": "x.xx.xx.xxx", "fixed_ip": null, "id": "10efed9c-9881-47b6-aa03-bdbb39b7decc", "pool": "ext_net"}, ...`

In the OpenStack v2.1 API which is documented at http://developer.openstack.org/api-ref-compute-v2.1.html, the same API call is not an extension any more, and it is named 'List Floating IP addresses'.  In the v2.1 API there is a 'status' value returned.

**Comment by meteorfox** [comment] 2016-02-29 22:35
@cbhall Thanks for reporting this issue. I believe this should be fixed on master already. We pinned the version to v2.1 due to similar issues. See https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/829

Try the master branch with the latest commit, if it's still not working I'll take a look. Thanks!

**Comment by voellm** [comment] 2016-02-29 22:36
+Carlos +Mateusz

On Mon, Feb 29, 2016 at 2:30 PM, Brian Hall <notifications@github.com>
wrote:

> With PerfKit Benchmarker version 1.0.1, OpenStack Floating IPs that had
> been created but were currently unused were being reused by Benchmarker. In
> later releases (1.1.0 and 1.2.0) Benchmarker will never reuse an existing
> (but currently unused) Floating IP, but will instead always attempt to
> create a new one. In my tests, not reusing an existing Floating IP will
> result in a Benchmarker failure if no more Floating IPs can be created.
>
> I believe I know what the problem is. In the Bencharker versions 1.0.1
> code in providers/openstack/os_network.py, it looks for available existing
> Floating IPs with:
> floating_ips = self.__nclient.floating_ips.findall(
> fixed_ip=None,
> pool=self.ip_pool_name
> )
> In the later releases, this code was changed to:
> floating_ips = self.__nclient.floating_ips.findall(
> fixed_ip=None,
> pool=self.ip_pool_name,
> status='Down'
> )
>
> The problem is that Benchmarker is using the OpenStack v2.0 API which is
> documented at http://docs.clouda.ca/api/api-ref-compute-v2-ext.html. In
> that API a 'status' value is not returned by the 'List Floating IPs' API
> call. As an example, dumping the result of that API call on my OpenStack
> deployment, I see a result that looks like this (with the ip obscured):
> {"floating_ips": [{"instance_id": null, "ip": "x.xx.xx.xxx", "fixed_ip":
> null, "id": "10efed9c-9881-47b6-aa03-bdbb39b7decc", "pool": "ext_net"}, ...
>
> In the OpenStack v2.1 API which is documented at
> http://developer.openstack.org/api-ref-compute-v2.1.html, the same API
> call is not an extension any more, and it is named 'List Floating IP
> addresses'. In the v2.1 API there is a 'status' value returned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/854>.
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by meteorfox** [comment] 2016-02-29 22:44
@cbhall Also I forgot to add, make sure you run `pip install -r requirements-openstack.txt` so it pulls that version of `python-novaclient`.

**Comment by cbhall** [comment] 2016-03-01 22:23
I picked up the latest commit of the master branch, and I updated the Python packages to python-keystoneclient==2.1.1 and python-novaclient==2.35.0.  However, I still see the same problem.  Unfortunately, my OpenStack only supports the Nova v2.0 API:
# nova version-list
+------+-----------+----------------------+-------------+---------+
| Id   | Status    | Updated              | Min Version | Version |
+------+-----------+----------------------+-------------+---------+
| v2.0 | SUPPORTED | 2011-01-21T11:33:21Z |             |         |
+------+-----------+----------------------+-------------+---------+
As such, my understanding is that PerfKit is still using the Nova v2.0 API and getting a response back conforming to that version of the API (and thus will never see/match a 'status' value in the result).

**Comment by meteorfox** [comment] 2016-03-01 23:56
@cbhall I see. The reason we added the filter for `status='Down'` is that without it will try to re-use floating IPs that have been associated with an instance already and cause an error.

One solution to support both API version is to filter for those floating IPs that have a `"instance_id": null` instead of using `status`.

**Comment by cbhall** [comment] 2016-03-02 00:01
@meteorfox Sure, that sounds like a good alternative.

**Comment by meteorfox** [comment] 2016-03-08 19:41
I was able to replicate this bug in my environment as well. I posted #862 to address the issue.

**Comment by cbhall** [comment] 2016-03-10 15:44
This fix is working just fine for me.  In addition, the new code is correctly deleting the floating IP after use, another issue I had noted in past.

**Comment by voellm** [comment] 2016-03-14 17:33
Ready for review and to complete the integration?

**Comment by meteorfox** [comment] 2016-03-14 17:35
Yes, PR #862 which addresses this issue is ready for review.

**Comment by meteorfox** [comment] 2016-03-21 18:56
Closing since #862 has already been merged and has been confirmed to address this issue.

Please feel free to re-open if the issue is still present.

**Closed by meteorfox** 2016-03-21 18:56 UTC
Labels: bug
