### ISSUE TITLE
SPEC CPU2006 run fails to delete VM on OpenStack

### ISSUE THREAD

**Issue by cbhall** [GoogleCloudPlatform/PerfKitBenchmarker#856] opened 2016-03-02 15:43 UTC
Running SPEC CPU2006 on OpenStack with:
`./pkb.trace.py --cloud=OpenStack --benchmarks=speccpu2006 --benchmark_subset=all --image="Ubuntu 14.04.3 LTS" --machine_type=m1.small --openstack_private_network=private_net --openstack_public_network=ext_net`
takes about 11 hours.  This run always fails to delete the VM that was created.  Dumping the API requests and responses indicates that the problem is as follows.  A delete request is made:
`DELETE /v2/4f299816e33f49c7ae3819ee2d7d19d9/servers/bbe3f0cc-04c6-46d4-87a7-5ab0f04d7e66`
and the response back is `Authentication required`.  Next, an attempt is made to authenticate using `POST /v2.0/tokens`, but the body of the request is missing a password:
`{"auth": {"passwordCredentials": {"username": "demo", "password": null}, "tenantId": "4f299816e33f49c7ae3819ee2d7d19d9"}}`
Obviously, many previous authentications have taken place with the right password.  This particular case though is the first attempt that used `passwordCredentials` with a `tenantId` (a number of previous cases used a `tenantName`).

**Comment by cbhall** [comment] 2016-03-02 21:19
I forgot to mention that there was also an exception reported:
```
Connectio2016-03-02 01:40:47,955 2b78f930 MainThread speccpu2006(1/1) ERROR    Exception occurred while calling DeleteVm(x.xx.xx.xxx):
Traceback (most recent call last):
  File ".../PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 245, in _ExecuteThreadCall
    queue.put(ThreadCallResult(call_id, target(*args, **kwargs), None))
  File ".../PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 307, in DeleteVm
    vm.Delete()
  File ".../PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 135, in Delete
    self._DeleteResource()
  File ".../PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 481, in WrappedFunction
    return f(*args, **kwargs)
  File ".../PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 117, in _DeleteResource
    self._Delete()
  File "...PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 481, in WrappedFunction
    return f(*args, **kwargs)
  File ".../PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/utils.py", line 158, in decor
    NovaClient.instance.reconnect()
AttributeError: type object 'NovaClient' has no attribute 'instance'

2016-03-02 01:40:47,955 2b78f930 MainThread speccpu2006(1/1) ERROR    Got an exception deleting VMs. Attempting to continue tearing down.
```

**Comment by voellm** [comment] 2016-03-02 21:40
Carlos - can you triage?

**Comment by cbhall** [comment] 2016-03-03 15:33
The authentication request that is missing a password actually comes from line 646 in /usr/local/lib/python2.7/site-packages/novaclient/client.py (in _v2_auth).  Note that this is with python-novaclient==2.35.0.

**Comment by voellm** [comment] 2016-03-03 21:48
@cbhall - Would you like to submit a fix we can review?

**Comment by cbhall** [comment] 2016-03-07 19:57
Sure, I will work on a fix.

**Comment by meteorfox** [comment] 2016-03-09 18:06
@kivio  is the author of the code so he should be able to know what's going on exactly, but I'll give it a try.

It looks like because the benchmark takes a long time then the auth token expires and it has to reauthenticate with Keystone.

Now, the retry logic is there but it relies on an try/except behavior combined with ` __getattribute__` from what I see.

This line throws the exception `AttributeError` like it shows in your stack trace:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/openstack/utils.py#L158

and this happens because there is actually no `instance` variable on the `NovaClient` object. This seems to be on purpose because then there is an override for ` __getattribute__` that looks like it was supposed to catch this exception and retry it first on an instance of `NovaClient`, and if that fails then on  `self.__client` which also has no `instance` variable hence raises the `AttributeError` again.

What is not very clear to me is why did it actually retry the `POST /v2.0/tokens` at all. Perhaps @kivio can give us more details.

Here are some options to fix this:
- Fix it to work how it was originally intended to. 
- Change it to use [Keystone Sessions](http://docs.openstack.org/developer/keystoneauth/using-sessions.html#using-sessions) which should handle automatic re-authentications when a token expires. (should be easy, I can tackle this if you haven't started on a solution yet)
- Change from using the library approach to using the CLIs instead to match other providers. (big effort, essentially a rewrite)

**Comment by cbhall** [comment] 2016-03-09 20:00
@meteorfox @kivio  Yes, the failure is caused because the benchmark runs for a long time and the auth token has expired.  I have investigated a couple of fixes and have some comments about the fixes and about the code in general.  Note that I don't generally program in Python and I don't know the Benchmarker code well, so my comments may be off base...

The first fix I considered was to modify the code throwing the exception, such that it would correctly call reconnect().  Here is one way to do that:
```
        def decor(self, *args, **kwargs):
            from novaclient.exceptions import Unauthorized
            try:
                return function(self, *args, **kwargs)
            except Unauthorized as e:
                NovaClient.reconnect(self.client)
                raise AuthException(str(e))
```
This code works, but I don't like it.  There are multiple instances of NovaClient floating around, and this code manages to use one of them and thus eliminates the exception.  It is actually one of the other NovaClient instances that is trying to do the DELETE request.  That other NovaClient instance later does an authorization request successfully, and then successfully DELETEs the VM.  In other words, making this code work really just eliminates the exception, and doesn't directly address the need for an authorization request that will allow the original API request to succeed when it is retried.

The second fix I tried is related to the authorization attempt that is missing a password.  That authorization request is generated entirely inside the novaclient package code.  If the novaclient package had been told the password, it would have used it.  Therefore, the second fix is in the NovaClient `__init__` code:
```
        self.__client = noclient.Client('2',
                                        self.user,
                                        self.password,
                                        self.tenant,
                                        self.url,
                                        auth_token=self.__auth.get_token(),
                                        tenant_id=self.__auth.get_tenant_id(),
                                        endpoint_type=self.endpoint_type,
                                        http_log_debug=self.http_log_debug,
                                        )
```
I like this fix better.  Using it actually means that the `decor` code will never see an Unauthorized exception from the `novaclient`, and it means that the `reconnect` code is unnecessary.

As a general comment on the Benchmarker code for OpenStack, I think it is undesirable that many different NovaClient instances are used.  If there were a single instance it would simplify things, and it would result in fewer API requests being done (each authorization is actually about 4 separate API requests).

**Comment by meteorfox** [comment] 2016-03-09 20:09
@cbhall I proposed PR #870 to address this issue.

Essentially, it's like you suggested as a 'second fix' but still uses Keystone, particularly their Session object, which apparently seems to be the recommended approach by the OpenStack docs.

Basically, Keystone Session manages the retry logic for whenever the auth token expires this means we can simplify our code in Benchmarker.

I'm currently testing it with a long running benchmark to make sure it works. The default token timeout is usually 1 hour, and I set my run for at least 65 minutes. I'll report back on the results once it finishes.

**Comment by meteorfox** [comment] 2016-03-09 21:40
heh.. I though I had the default token expiration timeout but I actually have 12 hours configured. *sigh*

I'll revoke the token manually. I should've probably done that from the beginning.

**Comment by meteorfox** [comment] 2016-03-09 22:21
@cbhall Alright, I confirmed that is properly reauthenticating.

Here's the log, 
- Tries deleting the server but gets an `Authentication required` error
- Automatically re-authenticates and gets a new token
- Retries the delete call, and gets a 204 response code

```
2016-03-09 22:11:03,740 b5890973 Thread-21 fio(1/1) session.py:198 DEBUG    REQ: curl -g -i -X DELETE http://172.29.236.10:8774/v2/c6d65efa00e64e64a2fc502119da1fec/servers/5fbd2d49-8d3e-4af4-9c20-edc2877e5b7e -H "User-Agent: python-novaclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}d66262bbceeedffd7944a868350d5498b5d539df"
9a76-5d76-4b40-8e01-0259bad51560 Connection: keep-alive Date: Wed, 09 Mar 2016 22:11:03 GMT Content-Type: text/plain Www-Authenticate: Keystone uri='http://172.29.236.10:5000' 
RESP BODY: Authentication required

2016-03-09 22:11:03,768 b5890973 Thread-21 fio(1/1) v2.py:86 DEBUG    Making authentication request to http://172.29.236.10:5000/v2.0/tokens
2016-03-09 22:11:04,062 b5890973 Thread-21 fio(1/1) session.py:216 DEBUG    RESP: [204] Date: Wed, 09 Mar 2016 22:11:04 GMT Connection: keep-alive Content-Type: application/json Content-Length: 0 X-Compute-Request-Id: req-688cce87-231b-4e5a-90ed-841f48db7b23
```

So, once the PR gets reviewed and merged this should fix your problem.

**Comment by cbhall** [comment] 2016-03-10 15:59
The new code is working just fine for me.  The number of API requests for authentication is substantially reduced.  Nice!

**Comment by meteorfox** [comment] 2016-03-21 18:56
Closing since #870 has already been merged and has been confirmed to address this issue.

Please feel free to re-open if the issue is still present.

**Closed by meteorfox** 2016-03-21 18:56 UTC
Labels: bug, P1
