### ISSUE TITLE
object_storage_service Benchmarking failes for Azure

### ISSUE THREAD

**Issue by amitpundir** [GoogleCloudPlatform/PerfKitBenchmarker#1111] opened 2016-09-20 11:29 UTC
I have tried it multiple time and also changed the base host to conduct test but object_storage_service test fails for Azure. 

Attached is console output of last failed test
[perfkit-bug.txt](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/482386/perfkit-bug.txt)

I strongly feel that test is not using values from --zones argument in later stage. following lines from the console output shows that its using "East US" location where as i have offered "North Europe" in the argument. 

```
2016-09-20 10:58:11,998 323af169 MainThread object_storage_service(1/1) INFO     Preparing benchmark object_storage_service
2016-09-20 10:58:12,003 323af169 MainThread object_storage_service(1/1) INFO     Running: azure storage account create --type ZRS -l East US pkb323af169
2016-09-20 10:58:14,370 323af169 MainThread object_storage_service(1/1) INFO     Ran azure storage account create --type ZRS -l East US pkb323af169. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The location constraint is not valid
error:   storage account create command failed
```

I also tried to conduct test in "East  US" location but that also fails with error that creation of affinity group is not permitted at location. It suggests to use some other location.

**Comment by noahl** [comment] 2016-09-20 18:00
@amitpundir you are right, it's not using the zones argument. I'm sorry, the calling convention for object storage is not very intuitive right now. You set the object storage region using the `--object_storage_region` flag. The `--zones` flag only controls VM placement. Although it is inconvenient, this does let you test any object storage region from any VM zone.

I think you know this, but for clarity to any other readers, the "location constraint is not valid" errors are coming from Azure. You will need to find a combination of `--zones` and `--object_storage_region` that Azure will accept. I have not tried North Europe, but East US 2 works well for me.

I'm closing this issue, but please do reopen if you think the issue is not fully resolved.

**Closed by noahl** 2016-09-20 18:00 UTC
